modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/CaliberMC/Buildify/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL = "https://modrinth.com/mod/buildify"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

# Optional Dependencies - Mod Compatibility
[[dependencies."${mod_id}"]]
modId="caliber"
mandatory=false
versionRange="${caliber_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="regions_unexplored"
mandatory=false
versionRange="${regions_unexplored_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="biomesoplenty"
mandatory=false
versionRange="${biomesoplenty_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create"
mandatory=false
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"