package com.calibermc.buildify.datagen.properties;

public enum CobbleBricksTypes {
    POLISHED_BASALT("minecraft:polished_basalt"),
    SMOOTH_BASALT("minecraft:smooth_basalt"),
    CHISELED_POLISHED_BLACKSTONE("minecraft:chiseled_polished_blackstone"),
    CHISELED_POLISHED_BLACKSTONE_BRICKS("minecraft:chiseled_polished_blackstone_bricks"),
    POLISHED_BLACKSTONE("minecraft:polished_blackstone"),
    POLISHED_BLACKSTONE_BRICKS("minecraft:polished_blackstone_bricks"),
    CHISELED_DEEPSLATE("minecraft:chiseled_deepslate"),
    COBBLED_DEEPSLATE("minecraft:cobbled_deepslate"),
    CRACKED_DEEPSLATE_BRICKS("minecraft:cracked_deepslate_bricks"),
    CRACKED_DEEPSLATE_TILES("minecraft:cracked_deepslate_tiles"),
    DEEPSLATE_BRICKS("minecraft:deepslate_bricks"),
    DEEPSLATE_TILES("minecraft:deepslate_tiles"),
    POLISHED_DEEPSLATE("minecraft:polished_deepslate"),
    POLISHED_GRANITE("minecraft:polished_granite"),
    CHISELED_NETHER_BRICKS("minecraft:chiseled_nether_bricks"),
    CRACKED_NETHER_BRICKS("minecraft:cracked_nether_bricks"),
    NETHER_BRICKS("minecraft:nether_bricks"),
    RED_NETHER_BRICKS("minecraft:red_nether_bricks"),
    CHISELED_RED_SANDSTONE("minecraft:chiseled_red_sandstone"),
    CUT_RED_SANDSTONE("minecraft:cut_red_sandstone"),
    SMOOTH_RED_SANDSTONE("minecraft:smooth_red_sandstone"),
    CHISELED_SANDSTONE("minecraft:chiseled_sandstone"),
    CUT_SANDSTONE("minecraft:cut_sandstone"),
    SMOOTH_SANDSTONE("minecraft:smooth_sandstone"),
    STONE_BRICKS("minecraft:stone_bricks"),
    CRACKED_STONE_BRICKS("minecraft:cracked_stone_bricks"),
    MOSSY_STONE_BRICKS("minecraft:mossy_stone_bricks"),
    CHISELED_STONE_BRICKS("minecraft:chiseled_stone_bricks"),
    COBBLESTONE("minecraft:cobblestone"),
    MOSSY_COBBLESTONE("minecraft:mossy_cobblestone"),
    SMOOTH_STONE("minecraft:smooth_stone"),
    BRICKS("minecraft:bricks"),
    MUD_BRICKS("minecraft:mud_bricks"),
    POLISHED_ANDESITE("minecraft:polished_andesite"),
    POLISHED_DIORITE("minecraft:polished_diorite"),
    PRISMARINE_BRICKS("minecraft:prismarine_bricks"),
    DARK_PRISMARINE("minecraft:dark_prismarine"),
    QUARTZ_BRICKS("minecraft:quartz_bricks"),
    CHISELED_QUARTZ_BLOCK("minecraft:chiseled_quartz_block"),
    PURPUR_BLOCK("minecraft:purpur_block"),
    PURPUR_PILLAR("minecraft:purpur_pillar"),

    // Biomes O' Plenty
    BOP_BRIMSTONE_BRICKS("biomesoplenty:brimstone_bricks"),
    BOP_CHISELED_BRIMSTONE_BRICKS("biomesoplenty:chiseled_brimstone_bricks"),
    BOP_CHISELED_BLACK_SANDSTONE("biomesoplenty:chiseled_black_sandstone"),
    BOP_CHISELED_ORANGE_SANDSTONE("biomesoplenty:chiseled_orange_sandstone"),
    BOP_CHISELED_WHITE_SANDSTONE("biomesoplenty:chiseled_white_sandstone"),
    BOP_CUT_BLACK_SANDSTONE("biomesoplenty:cut_black_sandstone"),
    BOP_CUT_ORANGE_SANDSTONE("biomesoplenty:cut_orange_sandstone"),
    BOP_CUT_WHITE_SANDSTONE("biomesoplenty:cut_white_sandstone"),
    BOP_SMOOTH_BLACK_SANDSTONE("biomesoplenty:smooth_black_sandstone"),
    BOP_SMOOTH_ORANGE_SANDSTONE("biomesoplenty:smooth_orange_sandstone"),
    BOP_SMOOTH_WHITE_SANDSTONE("biomesoplenty:smooth_white_sandstone"),

    // Chipped
//    CHIPPED_AMETHYST_BLOCK_BRICKS("chipped:amethyst_block_bricks"),
//    CHIPPED_AMETHYST_BLOCK_MINI_TILES("chipped:amethyst_block_mini_tiles"),
//    CHIPPED_AMETHYST_BLOCK_PILLAR("chipped:amethyst_block_pillar"),
//    CHIPPED_AMETHYST_BLOCK_PILLAR_TOP("chipped:amethyst_block_pillar_top"),
//    CHIPPED_AMETHYST_BLOCK_SCALES("chipped:amethyst_block_scales"),
//    CHIPPED_ANGRY_AMETHYST_BLOCK("chipped:angry_amethyst_block"),
//    CHIPPED_BLANK_AMETHYST_BLOCK_CARVING("chipped:blank_amethyst_block_carving"),
//    CHIPPED_CARVED_AMETHYST_BLOCK("chipped:carved_amethyst_block"),
//    CHIPPED_CHECKERED_AMETHYST_BLOCK_TILES("chipped:checkered_amethyst_block_tiles"),
//    CHIPPED_COBBLED_AMETHYST_BLOCK("chipped:cobbled_amethyst_block"),
//    CHIPPED_CRACKED_AMETHYST_BLOCK_BRICKS("chipped:cracked_amethyst_block_bricks"),
//    CHIPPED_CRACKED_DISORDERED_AMETHYST_BLOCK_BRICKS("chipped:cracked_disordered_amethyst_block_bricks"),
//    CHIPPED_CRACKED_FLAT_AMETHYST_BLOCK_TILES("chipped:cracked_flat_amethyst_block_tiles"),
//    CHIPPED_CREEPER_AMETHYST_BLOCK_CARVING("chipped:creeper_amethyst_block_carving"),
//    CHIPPED_CRYING_AMETHYST_BLOCK("chipped:crying_amethyst_block"),
//    CHIPPED_CUT_BLANK_AMETHYST_BLOCK("chipped:cut_blank_amethyst_block"),
//    CHIPPED_GLAD_AMETHYST_BLOCK("chipped:glad_amethyst_block"),
//    CHIPPED_DUH_AMETHYST_BLOCK("chipped:duh_amethyst_block"),
//    CHIPPED_ENGRAVED_AMETHYST_BLOCK("chipped:engraved_amethyst_block"),
//    CHIPPED_ERODED_AMETHYST_BLOCK("chipped:eroded_amethyst_block"),
//    CHIPPED_ETCHED_AMETHYST_BLOCK_BRICKS("chipped:etched_amethyst_block_bricks"),
//    CHIPPED_FLAT_AMETHYST_BLOCK_TILES("chipped:flat_amethyst_block_tiles"),
//    CHIPPED_INLAYED_AMETHYST_BLOCK("chipped:inlayed_amethyst_block"),
//    CHIPPED_INSCRIBED_AMETHYST_BLOCK("chipped:inscribed_amethyst_block"),
//    CHIPPED_LAYED_AMETHYST_BLOCK_BRICKS("chipped:layed_amethyst_block_bricks"),
//    CHIPPED_LODED_AMETHYST_BLOCK("chipped:loded_amethyst_block"),
//    CHIPPED_OFFSET_AMETHYST_BLOCK_BRICKS("chipped:offset_amethyst_block_bricks"),
//    CHIPPED_PILLAR_AMETHYST_BLOCK_BRICKS("chipped:pillar_amethyst_block_bricks"),
//    CHIPPED_PRISMAL_AMETHYST_BLOCK_REMNANTS("chipped:prismal_amethyst_block_remnants"),
//    CHIPPED_ROUGH_AMETHYST_BLOCK("chipped:rough_amethyst_block"),
//    CHIPPED_ROUNDED_AMETHYST_BLOCK_BRICKS("chipped:rounded_amethyst_block_bricks"),
//    CHIPPED_RUNIC_CARVED_AMETHYST_BLOCK("chipped:runic_carved_amethyst_block"),
//    CHIPPED_SAD_AMETHYST_BLOCK("chipped:sad_amethyst_block"),
//    CHIPPED_SANDED_AMETHYST_BLOCK("chipped:sanded_amethyst_block"),
//    CHIPPED_SMALL_AMETHYST_BLOCK_BRICKS("chipped:small_amethyst_block_bricks"),
//    CHIPPED_SMOOTH_INLAYED_AMETHYST_BLOCK("chipped:smooth_inlayed_amethyst_block"),
//    CHIPPED_SMOOTH_RINGED_AMETHYST_BLOCK("chipped:smooth_ringed_amethyst_block"),
//    CHIPPED_SMOOTHED_DOUBLE_INLAYED_AMETHYST_BLOCK("chipped:smoothed_double_inlayed_amethyst_block"),
//    CHIPPED_SPIDER_AMETHYST_BLOCK_CARVING("chipped:spider_amethyst_block_carving"),
//    CHIPPED_SPIRALED_AMETHYST_BLOCK("chipped:spiraled_amethyst_block"),
//    CHIPPED_STACKED_AMETHYST_BLOCK_BRICKS("chipped:stacked_amethyst_block_bricks"),
//    CHIPPED_TILED_AMETHYST_BLOCK("chipped:tiled_amethyst_block"),
//    CHIPPED_TINY_AMETHYST_BLOCK_BRICKS("chipped:tiny_amethyst_block_bricks"),
//    CHIPPED_TINY_LAYERED_AMETHYST_BLOCK_BRICKS("chipped:tiny_layered_amethyst_block_bricks"),
//    CHIPPED_TINY_LAYERED_AMETHYST_BLOCK_SLABS("chipped:tiny_layered_amethyst_block_slabs"),
//    CHIPPED_TRODDEN_AMETHYST_BLOCK("chipped:trodden_amethyst_block"),
//    CHIPPED_UNAMUSED_AMETHYST_BLOCK("chipped:unamused_amethyst_block"),
//    CHIPPED_VERTICAL_CUT_AMETHYST_BLOCK("chipped:vertical_cut_amethyst_block"),
//    CHIPPED_VERTICAL_DISORDERED_AMETHYST_BLOCK_BRICKS("chipped:vertical_disordered_amethyst_block_bricks"),
//    CHIPPED_WEATHERED_AMETHYST_BLOCK("chipped:weathered_amethyst_block"),
//    CHIPPED_BORDERED_AMETHYST_BLOCK("chipped:bordered_amethyst_block"),
//    CHIPPED_BRICK_BORDERED_AMETHYST_BLOCK("chipped:brick_bordered_amethyst_block"),
//    CHIPPED_CUT_AMETHYST_BLOCK_COLUMN("chipped:cut_amethyst_block_column"),
//    CHIPPED_EDGED_AMETHYST_BLOCK_BRICKS("chipped:edged_amethyst_block_bricks"),
//    CHIPPED_OVERLAPPING_AMETHYST_BLOCK_TILES("chipped:overlapping_amethyst_block_tiles"),
//    CHIPPED_POLISHED_AMETHYST_BLOCK("chipped:polished_amethyst_block"),
//    CHIPPED_SMOOTH_AMETHYST_BLOCK_COLUMN("chipped:smooth_amethyst_block_column"),
//    CHIPPED_THICK_INLAYED_AMETHYST_BLOCK("chipped:thick_inlayed_amethyst_block"),
//    CHIPPED_TILED_AMETHYST_BLOCK_COLUMN("chipped:tiled_amethyst_block_column"),
//    CHIPPED_TILED_BORDERED_AMETHYST_BLOCK("chipped:tiled_bordered_amethyst_block"),
//    CHIPPED_TINY_BRICK_BORDERED_AMETHYST_BLOCK("chipped:tiny_brick_bordered_amethyst_block"),
//    CHIPPED_CURLY_AMETHYST_BLOCK_PILLAR("chipped:curly_amethyst_block_pillar"),
//    CHIPPED_FINE_AMETHYST_BLOCK_PILLAR("chipped:fine_amethyst_block_pillar"),
//    CHIPPED_ORNATE_AMETHYST_BLOCK_PILLAR("chipped:ornate_amethyst_block_pillar"),
//    CHIPPED_SIMPLE_AMETHYST_BLOCK_PILLAR("chipped:simple_amethyst_block_pillar"),
//    CHIPPED_MASSIVE_AMETHYST_BLOCK_BRICKS("chipped:massive_amethyst_block_bricks"),
//
//    CHIPPED_COAL_BLOCK_BRICKS("chipped:coal_block_bricks"),
//    CHIPPED_COAL_BLOCK_MINI_TILES("chipped:coal_block_mini_tiles"),
//    CHIPPED_COAL_BLOCK_PILLAR("chipped:coal_block_pillar"),
//    CHIPPED_COAL_BLOCK_PILLAR_TOP("chipped:coal_block_pillar_top"),
//    CHIPPED_COAL_BLOCK_SCALES("chipped:coal_block_scales"),
//    CHIPPED_ANGRY_COAL_BLOCK("chipped:angry_coal_block"),
//    CHIPPED_BLANK_COAL_BLOCK_CARVING("chipped:blank_coal_block_carving"),
//    CHIPPED_CARVED_COAL_BLOCK("chipped:carved_coal_block"),
//    CHIPPED_CHECKERED_COAL_BLOCK_TILES("chipped:checkered_coal_block_tiles"),
//    CHIPPED_COBBLED_COAL_BLOCK("chipped:cobbled_coal_block"),
//    CHIPPED_CRACKED_COAL_BLOCK_BRICKS("chipped:cracked_coal_block_bricks"),
//    CHIPPED_CRACKED_DISORDERED_COAL_BLOCK_BRICKS("chipped:cracked_disordered_coal_block_bricks"),
//    CHIPPED_CRACKED_FLAT_COAL_BLOCK_TILES("chipped:cracked_flat_coal_block_tiles"),
//    CHIPPED_CREEPER_COAL_BLOCK_CARVING("chipped:creeper_coal_block_carving"),
//    CHIPPED_CRYING_COAL_BLOCK("chipped:crying_coal_block"),
//    CHIPPED_CUT_BLANK_COAL_BLOCK("chipped:cut_blank_coal_block"),
//    CHIPPED_GLAD_COAL_BLOCK("chipped:glad_coal_block"),
//    CHIPPED_DUH_COAL_BLOCK("chipped:duh_coal_block"),
//    CHIPPED_ENGRAVED_COAL_BLOCK("chipped:engraved_coal_block"),
//    CHIPPED_ERODED_COAL_BLOCK("chipped:eroded_coal_block"),
//    CHIPPED_ETCHED_COAL_BLOCK_BRICKS("chipped:etched_coal_block_bricks"),
//    CHIPPED_FLAT_COAL_BLOCK_TILES("chipped:flat_coal_block_tiles"),
//    CHIPPED_INLAYED_COAL_BLOCK("chipped:inlayed_coal_block"),
//    CHIPPED_INSCRIBED_COAL_BLOCK("chipped:inscribed_coal_block"),
//    CHIPPED_LAYED_COAL_BLOCK_BRICKS("chipped:layed_coal_block_bricks"),
//    CHIPPED_LODED_COAL_BLOCK("chipped:loded_coal_block"),
//    CHIPPED_OFFSET_COAL_BLOCK_BRICKS("chipped:offset_coal_block_bricks"),
//    CHIPPED_PILLAR_COAL_BLOCK_BRICKS("chipped:pillar_coal_block_bricks"),
//    CHIPPED_PRISMAL_COAL_BLOCK_REMNANTS("chipped:prismal_coal_block_remnants"),
//    CHIPPED_ROUGH_COAL_BLOCK("chipped:rough_coal_block"),
//    CHIPPED_ROUNDED_COAL_BLOCK_BRICKS("chipped:rounded_coal_block_bricks"),
//    CHIPPED_RUNIC_CARVED_COAL_BLOCK("chipped:runic_carved_coal_block"),
//    CHIPPED_SAD_COAL_BLOCK("chipped:sad_coal_block"),
//    CHIPPED_SANDED_COAL_BLOCK("chipped:sanded_coal_block"),
//    CHIPPED_SMALL_COAL_BLOCK_BRICKS("chipped:small_coal_block_bricks"),
//    CHIPPED_SMOOTH_INLAYED_COAL_BLOCK("chipped:smooth_inlayed_coal_block"),
//    CHIPPED_SMOOTH_RINGED_COAL_BLOCK("chipped:smooth_ringed_coal_block"),
//    CHIPPED_SMOOTHED_DOUBLE_INLAYED_COAL_BLOCK("chipped:smoothed_double_inlayed_coal_block"),
//    CHIPPED_SPIDER_COAL_BLOCK_CARVING("chipped:spider_coal_block_carving"),
//    CHIPPED_SPIRALED_COAL_BLOCK("chipped:spiraled_coal_block"),
//    CHIPPED_STACKED_COAL_BLOCK_BRICKS("chipped:stacked_coal_block_bricks"),
//    CHIPPED_TILED_COAL_BLOCK("chipped:tiled_coal_block"),
//    CHIPPED_TINY_COAL_BLOCK_BRICKS("chipped:tiny_coal_block_bricks"),
//    CHIPPED_TINY_LAYERED_COAL_BLOCK_BRICKS("chipped:tiny_layered_coal_block_bricks"),
//    CHIPPED_TINY_LAYERED_COAL_BLOCK_SLABS("chipped:tiny_layered_coal_block_slabs"),
//    CHIPPED_TRODDEN_COAL_BLOCK("chipped:trodden_coal_block"),
//    CHIPPED_UNAMUSED_COAL_BLOCK("chipped:unamused_coal_block"),
//    CHIPPED_VERTICAL_CUT_COAL_BLOCK("chipped:vertical_cut_coal_block"),
//    CHIPPED_VERTICAL_DISORDERED_COAL_BLOCK_BRICKS("chipped:vertical_disordered_coal_block_bricks"),
//    CHIPPED_WEATHERED_COAL_BLOCK("chipped:weathered_coal_block"),
//    CHIPPED_BORDERED_COAL_BLOCK("chipped:bordered_coal_block"),
//    CHIPPED_BRICK_BORDERED_COAL_BLOCK("chipped:brick_bordered_coal_block"),
//    CHIPPED_CUT_COAL_BLOCK_COLUMN("chipped:cut_coal_block_column"),
//    CHIPPED_EDGED_COAL_BLOCK_BRICKS("chipped:edged_coal_block_bricks"),
//    CHIPPED_OVERLAPPING_COAL_BLOCK_TILES("chipped:overlapping_coal_block_tiles"),
//    CHIPPED_POLISHED_COAL_BLOCK("chipped:polished_coal_block"),
//    CHIPPED_SMOOTH_COAL_BLOCK_COLUMN("chipped:smooth_coal_block_column"),
//    CHIPPED_THICK_INLAYED_COAL_BLOCK("chipped:thick_inlayed_coal_block"),
//    CHIPPED_TILED_COAL_BLOCK_COLUMN("chipped:tiled_coal_block_column"),
//    CHIPPED_TILED_BORDERED_COAL_BLOCK("chipped:tiled_bordered_coal_block"),
//    CHIPPED_TINY_BRICK_BORDERED_COAL_BLOCK("chipped:tiny_brick_bordered_coal_block"),
//    CHIPPED_CURLY_COAL_BLOCK_PILLAR("chipped:curly_coal_block_pillar"),
//    CHIPPED_FINE_COAL_BLOCK_PILLAR("chipped:fine_coal_block_pillar"),
//    CHIPPED_ORNATE_COAL_BLOCK_PILLAR("chipped:ornate_coal_block_pillar"),
//    CHIPPED_SIMPLE_COAL_BLOCK_PILLAR("chipped:simple_coal_block_pillar"),
//    CHIPPED_MASSIVE_COAL_BLOCK_BRICKS("chipped:massive_coal_block_bricks"),
//
//    CHIPPED_CRYING_OBSIDIAN_BRICKS("chipped:crying_obsidian_bricks"),
//    CHIPPED_CRYING_OBSIDIAN_MINI_TILES("chipped:crying_obsidian_mini_tiles"),
//    CHIPPED_CRYING_OBSIDIAN_PILLAR("chipped:crying_obsidian_pillar"),
//    CHIPPED_CRYING_OBSIDIAN_PILLAR_TOP("chipped:crying_obsidian_pillar_top"),
//    CHIPPED_CRYING_OBSIDIAN_SCALES("chipped:crying_obsidian_scales"),
//    CHIPPED_ANGRY_CRYING_OBSIDIAN("chipped:angry_crying_obsidian"),
//    CHIPPED_BLANK_CRYING_OBSIDIAN_CARVING("chipped:blank_crying_obsidian_carving"),
//    CHIPPED_CARVED_CRYING_OBSIDIAN("chipped:carved_crying_obsidian"),
//    CHIPPED_CHECKERED_CRYING_OBSIDIAN_TILES("chipped:checkered_crying_obsidian_tiles"),
//    CHIPPED_COBBLED_CRYING_OBSIDIAN("chipped:cobbled_crying_obsidian"),
//    CHIPPED_CRACKED_CRYING_OBSIDIAN_BRICKS("chipped:cracked_crying_obsidian_bricks"),
//    CHIPPED_CRACKED_DISORDERED_CRYING_OBSIDIAN_BRICKS("chipped:cracked_disordered_crying_obsidian_bricks"),
//    CHIPPED_CRACKED_FLAT_CRYING_OBSIDIAN_TILES("chipped:cracked_flat_crying_obsidian_tiles"),
//    CHIPPED_CREEPER_CRYING_OBSIDIAN_CARVING("chipped:creeper_crying_obsidian_carving"),
//    CHIPPED_CRYING_CRYING_OBSIDIAN("chipped:crying_crying_obsidian"),
//    CHIPPED_CUT_BLANK_CRYING_OBSIDIAN("chipped:cut_blank_crying_obsidian"),
//    CHIPPED_GLAD_CRYING_OBSIDIAN("chipped:glad_crying_obsidian"),
//    CHIPPED_DUH_CRYING_OBSIDIAN("chipped:duh_crying_obsidian"),
//    CHIPPED_ENGRAVED_CRYING_OBSIDIAN("chipped:engraved_crying_obsidian"),
//    CHIPPED_ERODED_CRYING_OBSIDIAN("chipped:eroded_crying_obsidian"),
//    CHIPPED_ETCHED_CRYING_OBSIDIAN_BRICKS("chipped:etched_crying_obsidian_bricks"),
//    CHIPPED_FLAT_CRYING_OBSIDIAN_TILES("chipped:flat_crying_obsidian_tiles"),
//    CHIPPED_INLAYED_CRYING_OBSIDIAN("chipped:inlayed_crying_obsidian"),
//    CHIPPED_INSCRIBED_CRYING_OBSIDIAN("chipped:inscribed_crying_obsidian"),
//    CHIPPED_LAYED_CRYING_OBSIDIAN_BRICKS("chipped:layed_crying_obsidian_bricks"),
//    CHIPPED_LODED_CRYING_OBSIDIAN("chipped:loded_crying_obsidian"),
//    CHIPPED_OFFSET_CRYING_OBSIDIAN_BRICKS("chipped:offset_crying_obsidian_bricks"),
//    CHIPPED_PILLAR_CRYING_OBSIDIAN_BRICKS("chipped:pillar_crying_obsidian_bricks"),
//    CHIPPED_PRISMAL_CRYING_OBSIDIAN_REMNANTS("chipped:prismal_crying_obsidian_remnants"),
//    CHIPPED_ROUGH_CRYING_OBSIDIAN("chipped:rough_crying_obsidian"),
//    CHIPPED_ROUNDED_CRYING_OBSIDIAN_BRICKS("chipped:rounded_crying_obsidian_bricks"),
//    CHIPPED_RUNIC_CARVED_CRYING_OBSIDIAN("chipped:runic_carved_crying_obsidian"),
//    CHIPPED_SAD_CRYING_OBSIDIAN("chipped:sad_crying_obsidian"),
//    CHIPPED_SANDED_CRYING_OBSIDIAN("chipped:sanded_crying_obsidian"),
//    CHIPPED_SMALL_CRYING_OBSIDIAN_BRICKS("chipped:small_crying_obsidian_bricks"),
//    CHIPPED_SMOOTH_INLAYED_CRYING_OBSIDIAN("chipped:smooth_inlayed_crying_obsidian"),
//    CHIPPED_SMOOTH_RINGED_CRYING_OBSIDIAN("chipped:smooth_ringed_crying_obsidian"),
//    CHIPPED_SMOOTHED_DOUBLE_INLAYED_CRYING_OBSIDIAN("chipped:smoothed_double_inlayed_crying_obsidian"),
//    CHIPPED_SPIDER_CRYING_OBSIDIAN_CARVING("chipped:spider_crying_obsidian_carving"),
//    CHIPPED_SPIRALED_CRYING_OBSIDIAN("chipped:spiraled_crying_obsidian"),
//    CHIPPED_STACKED_CRYING_OBSIDIAN_BRICKS("chipped:stacked_crying_obsidian_bricks"),
//    CHIPPED_TILED_CRYING_OBSIDIAN("chipped:tiled_crying_obsidian"),
//    CHIPPED_TINY_CRYING_OBSIDIAN_BRICKS("chipped:tiny_crying_obsidian_bricks"),
//    CHIPPED_TINY_LAYERED_CRYING_OBSIDIAN_BRICKS("chipped:tiny_layered_crying_obsidian_bricks"),
//    CHIPPED_TINY_LAYERED_CRYING_OBSIDIAN_SLABS("chipped:tiny_layered_crying_obsidian_slabs"),
//    CHIPPED_TRODDEN_CRYING_OBSIDIAN("chipped:trodden_crying_obsidian"),
//    CHIPPED_UNAMUSED_CRYING_OBSIDIAN("chipped:unamused_crying_obsidian"),
//    CHIPPED_VERTICAL_CUT_CRYING_OBSIDIAN("chipped:vertical_cut_crying_obsidian"),
//    CHIPPED_VERTICAL_DISORDERED_CRYING_OBSIDIAN_BRICKS("chipped:vertical_disordered_crying_obsidian_bricks"),
//    CHIPPED_WEATHERED_CRYING_OBSIDIAN("chipped:weathered_crying_obsidian"),
//    CHIPPED_BORDERED_CRYING_OBSIDIAN("chipped:bordered_crying_obsidian"),
//    CHIPPED_BRICK_BORDERED_CRYING_OBSIDIAN("chipped:brick_bordered_crying_obsidian"),
//    CHIPPED_CUT_CRYING_OBSIDIAN_COLUMN("chipped:cut_crying_obsidian_column"),
//    CHIPPED_EDGED_CRYING_OBSIDIAN_BRICKS("chipped:edged_crying_obsidian_bricks"),
//    CHIPPED_OVERLAPPING_CRYING_OBSIDIAN_TILES("chipped:overlapping_crying_obsidian_tiles"),
//    CHIPPED_POLISHED_CRYING_OBSIDIAN("chipped:polished_crying_obsidian"),
//    CHIPPED_SMOOTH_CRYING_OBSIDIAN_COLUMN("chipped:smooth_crying_obsidian_column"),
//    CHIPPED_THICK_INLAYED_CRYING_OBSIDIAN("chipped:thick_inlayed_crying_obsidian"),
//    CHIPPED_TILED_CRYING_OBSIDIAN_COLUMN("chipped:tiled_crying_obsidian_column"),
//    CHIPPED_TILED_BORDERED_CRYING_OBSIDIAN("chipped:tiled_bordered_crying_obsidian"),
//    CHIPPED_TINY_BRICK_BORDERED_CRYING_OBSIDIAN("chipped:tiny_brick_bordered_crying_obsidian"),
//    CHIPPED_CURLY_CRYING_OBSIDIAN_PILLAR("chipped:curly_crying_obsidian_pillar"),
//    CHIPPED_FINE_CRYING_OBSIDIAN_PILLAR("chipped:fine_crying_obsidian_pillar"),
//    CHIPPED_ORNATE_CRYING_OBSIDIAN_PILLAR("chipped:ornate_crying_obsidian_pillar"),
//    CHIPPED_SIMPLE_CRYING_OBSIDIAN_PILLAR("chipped:simple_crying_obsidian_pillar"),
//    CHIPPED_MASSIVE_CRYING_OBSIDIAN_BRICKS("chipped:massive_crying_obsidian_bricks"),


    // Create
    CREATE_ANDESITE_PILLAR("create:andesite_pillar"),
    CREATE_ASURINE_PILLAR("create:asurine_pillar"),
    CREATE_CALCITE_PILLAR("create:calcite_pillar"),
    CREATE_CRIMSITE_PILLAR("create:crimsite_pillar"),
    CREATE_DEEPSLAITE_PILLAR("create:deepslate_pillar"),
    CREATE_DIORITE_PILLAR("create:diorite_pillar"),
    CREATE_DRIPSTONE_PILLAR("create:dripstone_pillar"),
    CREATE_GRANITE_PILLAR("create:granite_pillar"),
    CREATE_LIMESTONE_PILLAR("create:limestone_pillar"),
    CREATE_OCHRUM_PILLAR("create:ochrum_pillar"),
    CREATE_SCORIA_PILLAR("create:scoria_pillar"),
    CREATE_SCORCHIA_PILLAR("create:scorchia_pillar"),
    CREATE_TUFF_PILLAR("create:tuff_pillar"),
    CREATE_VERIDIUM_PILLAR("create:veridium_pillar"),
    CREATE_CUT_ANDESITE("create:cut_andesite"),
    CREATE_CUT_ASURINE("create:cut_asurine"),
    CREATE_CUT_CALCITE("create:cut_calcite"),
    CREATE_CUT_CRIMSITE("create:cut_crimsite"),
    CREATE_CUT_DEEPSLATE("create:cut_deepslate"),
    CREATE_CUT_DIORITE("create:cut_diorite"),
    CREATE_CUT_DRIPSTONE("create:cut_dripstone"),
    CREATE_CUT_GRANITE("create:cut_granite"),
    CREATE_CUT_LIMESTONE("create:cut_limestone"),
    CREATE_CUT_OCHRUM("create:cut_ochrum"),
    CREATE_CUT_SCORIA("create:cut_scoria"),
    CREATE_CUT_SCORCHIA("create:cut_scorchia"),
    CREATE_CUT_TUFF("create:cut_tuff"),
    CREATE_CUT_VERIDIUM("create:cut_veridium"),
    CREATE_CUT_ANDESITE_BRICKS("create:cut_andesite_bricks"),
    CREATE_CUT_ASURINE_BRICKS("create:cut_asurine_bricks"),
    CREATE_CUT_CALCITE_BRICKS("create:cut_calcite_bricks"),
    CREATE_CUT_CRIMSITE_BRICKS("create:cut_crimsite_bricks"),
    CREATE_CUT_DEEPSLATE_BRICKS("create:cut_deepslate_bricks"),
    CREATE_CUT_DIORITE_BRICKS("create:cut_diorite_bricks"),
    CREATE_CUT_DRIPSTONE_BRICKS("create:cut_dripstone_bricks"),
    CREATE_CUT_GRANITE_BRICKS("create:cut_granite_bricks"),
    CREATE_CUT_LIMESTONE_BRICKS("create:cut_limestone_bricks"),
    CREATE_CUT_OCHRUM_BRICKS("create:cut_ochrum_bricks"),
    CREATE_CUT_SCORIA_BRICKS("create:cut_scoria_bricks"),
    CREATE_CUT_SCORCHIA_BRICKS("create:cut_scorchia_bricks"),
    CREATE_CUT_TUFF_BRICKS("create:cut_tuff_bricks"),
    CREATE_CUT_VERIDIUM_BRICKS("create:cut_veridium_bricks"),
    CREATE_LAYERED_ANDESITE("create:layered_andesite"),
    CREATE_LAYERED_ASURINE("create:layered_asurine"),
    CREATE_LAYERED_CALCITE("create:layered_calcite"),
    CREATE_LAYERED_CRIMSITE("create:layered_crimsite"),
    CREATE_LAYERED_DEEPSLATE("create:layered_deepslate"),
    CREATE_LAYERED_DIORITE("create:layered_diorite"),
    CREATE_LAYERED_DRIPSTONE("create:layered_dripstone"),
    CREATE_LAYERED_GRANITE("create:layered_granite"),
    CREATE_LAYERED_LIMESTONE("create:layered_limestone"),
    CREATE_LAYERED_OCHRUM("create:layered_ochrum"),
    CREATE_LAYERED_SCORIA("create:layered_scoria"),
    CREATE_LAYERED_SCORCHIA("create:layered_scorchia"),
    CREATE_LAYERED_TUFF("create:layered_tuff"),
    CREATE_LAYERED_VERIDIUM("create:layered_veridium"),
    CREATE_POLISHED_CUT_ANDESITE("create:polished_cut_andesite"),
    CREATE_POLISHED_CUT_ASURINE("create:polished_cut_asurine"),
    CREATE_POLISHED_CUT_CALCITE("create:polished_cut_calcite"),
    CREATE_POLISHED_CUT_CRIMSITE("create:polished_cut_crimsite"),
    CREATE_POLISHED_CUT_DEEPSLATE("create:polished_cut_deepslate"),
    CREATE_POLISHED_CUT_DIORITE("create:polished_cut_diorite"),
    CREATE_POLISHED_CUT_DRIPSTONE("create:polished_cut_dripstone"),
    CREATE_POLISHED_CUT_GRANITE("create:polished_cut_granite"),
    CREATE_POLISHED_CUT_LIMESTONE("create:polished_cut_limestone"),
    CREATE_POLISHED_CUT_OCHRUM("create:polished_cut_ochrum"),
    CREATE_POLISHED_CUT_SCORIA("create:polished_cut_scoria"),
    CREATE_POLISHED_CUT_SCORCHIA("create:polished_cut_scorchia"),
    CREATE_POLISHED_CUT_TUFF("create:polished_cut_tuff"),
    CREATE_POLISHED_CUT_VERIDIUM("create:polished_cut_veridium"),
    CREATE_SMALL_ANDESITE_BRICKS("create:small_andesite_bricks"),
    CREATE_SMALL_ASURINE_BRICKS("create:small_asurine_bricks"),
    CREATE_SMALL_CALCITE_BRICKS("create:small_calcite_bricks"),
    CREATE_SMALL_CRIMSITE_BRICKS("create:small_crimsite_bricks"),
    CREATE_SMALL_DEEPSLATE_BRICKS("create:small_deepslate_bricks"),
    CREATE_SMALL_DIORITE_BRICKS("create:small_diorite_bricks"),
    CREATE_SMALL_DRIPSTONE_BRICKS("create:small_dripstone_bricks"),
    CREATE_SMALL_GRANITE_BRICKS("create:small_granite_bricks"),
    CREATE_SMALL_LIMESTONE_BRICKS("create:small_limestone_bricks"),
    CREATE_SMALL_OCHRUM_BRICKS("create:small_ochrum_bricks"),
    CREATE_SMALL_SCORIA_BRICKS("create:small_scoria_bricks"),
    CREATE_SMALL_SCORCHIA_BRICKS("create:small_scorchia_bricks"),
    CREATE_SMALL_TUFF_BRICKS("create:small_tuff_bricks"),
    CREATE_SMALL_VERIDIUM_BRICKS("create:small_veridium_bricks"),

    // Regions Unexplored
    RU_CHALK_BRICKS("regions_unexplored:chalk_bricks"),
    RU_CHALK_PILLAR("regions_unexplored:chalk_pillar");

    private final String name;

    CobbleBricksTypes(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
